const wordData = [
{ word: "春节", meaning: "Spring Festival; Lunar New Year", example: "春节的时候，我们全家一起吃年夜饭。(During the Spring Festival, our whole family eats New Year’s Eve dinner together.)" },
{ word: "要求", meaning: "requirement; request; demand", example: "这个作业的要求是写一篇三百字的文章。(The requirement for this assignment is to write a 300-character composition.)" },
{ word: "修改", meaning: "to revise; to correct; to edit", example: "老师帮我修改作文，让内容更清楚。(The teacher helped me revise my composition to make the content clearer.)" },
{ word: "完成", meaning: "to finish; to complete", example: "我晚上十点前就完成作业了。(I finished my homework before ten at night.)" },
{ word: "寒假", meaning: "winter vacation", example: "寒假我们打算回老家过年。(During winter vacation, we plan to go back to our hometown for the New Year.)" },
{ word: "过年", meaning: "to celebrate the Chinese New Year/ Lunar New Year", example: "很多在外地工作的人都会回家过年。(Many people who work away from home go back home to celebrate the New Year.)" },
{ word: "从来", meaning: "ever; (often with 不/没) never", example: "我从来没看过这么热闹的夜市。(I have never seen such a lively night market.)" },
{ word: "除夕", meaning: "Lunar New Year’s Eve", example: "除夕晚上我们一家人一起守岁看电视。(On New Year’s Eve our family stays up together and watches TV.)" },
{ word: "接着", meaning: "then; next; after that", example: "吃完年夜饭，接着我们一起去看烟火。(After finishing New Year’s Eve dinner, we then go watch the fireworks together.)" },
{ word: "爷爷", meaning: "grandfather (father’s father)", example: "爷爷每天早上带我去公园散步。(Grandpa takes me to the park for a walk every morning.)" },
{ word: "奶奶", meaning: "grandmother (father’s mother)", example: "奶奶做的菜最好吃。(Grandma’s cooking is the best.)" },
{ word: "拜拜", meaning: "to pray; to worship", example: "过年时，我们一早就去庙里拜拜。(At New Year, we go to the temple early in the morning to pray.)" },
{ word: "拜", meaning: "to pray; to worship", example: "我们在桌前拜祖先，谢谢他们的保佑。(We worship our ancestors in front of the table and thank them for their protection.)" },
{ word: "祖先", meaning: "ancestors", example: "过年时，家人一起拜祖先，表示感谢。(During the New Year, the family worships the ancestors together to show gratitude.)" },
{ word: "聚", meaning: "to gather; to get together", example: "过年的时候，亲戚都聚在一起吃饭。(During the New Year, relatives all gather together to eat.)" },
{ word: "煮", meaning: "to cook; to boil", example: "今天晚上我要煮一大锅水饺。(Tonight I’m going to cook a big pot of dumplings.)" },
{ word: "水饺", meaning: "dumplings", example: "过年的时候，我们常常全家一起包水饺。(During the New Year, our whole family often makes dumplings together.)" },
{ word: "炒", meaning: "to stir-fry", example: "妈妈在厨房炒青菜和肉片。(Mom is in the kitchen stir-frying vegetables and sliced meat.)" },
{ word: "米粉", meaning: "rice noodles", example: "我最喜欢吃妈妈煮的米粉。(I like the rice vermicelli my mom cooks the most.)" },
{ word: "煎", meaning: "to fry; to pan-fry", example: "早餐我想吃煎蛋和煎萝卜糕。(For breakfast I want to eat fried eggs and pan-fried radish cake.)" },
{ word: "萝卜", meaning: "radish", example: "桌上有一大盘切好的萝卜。(There is a big plate of sliced radishes on the table.)" },
{ word: "等等", meaning: "etc.; and so on", example: "桌上有苹果、橘子、葡萄等等。(There are apples, oranges, grapes, etc. on the table.)" },
{ word: "发财", meaning: "to get rich; to make a fortune", example: "过年大家互相说「恭喜发财」。(During the New Year, everyone says “Gongxi facai” to wish each other wealth.)" },
{ word: "橘子", meaning: "orange; tangerine", example: "过年家里一定会买很多橘子。(For New Year, our family always buys lots of tangerines.)" },
{ word: "更加", meaning: "even more", example: "听完故事后，我更加了解春节的文化。(After hearing the story, I understand Spring Festival culture even more.)" },
{ word: "响", meaning: "to ring; to sound; to make a noise", example: "十二点一到，鞭炮就响了起来。(As soon as it struck midnight, the firecrackers started going off.)" },
{ word: "舅舅", meaning: "mother’s brother; uncle (on maternal side)", example: "寒假的时候，我去舅舅家玩。(During winter vacation, I go to my uncle’s house to play.)" },
{ word: "舅妈", meaning: "aunt (wife of mother’s brother", example: "舅妈做的菜很好吃。(The dishes my aunt makes are very delicious.)" },
{ word: "亲切", meaning: "kind; friendly; warm (in manner)", example: "那位老师很亲切，常常关心学生。(That teacher is very kind and often cares about the students.)" },
{ word: "相当", meaning: "quite; rather; fairly", example: "今天外面相当冷，出门要多穿一点。(It’s quite cold outside today; wear more if you go out.)" },
{ word: "温暖", meaning: "warm; warmth (literal or emotional)", example: "家人的笑容让我觉得很温暖。(My family’s smiles make me feel very warm.)" },
{ word: "感谢", meaning: "to thank; to be grateful; gratitude", example: "谢谢你帮我，我真的很感谢你。(Thank you for helping me, I’m really grateful to you.)" },
{ word: "年夜饭", meaning: "reunion dinner on Chinese New Year’s Eve", example: "我们一家人一起吃年夜饭，聊一年的事情。(Our family eats New Year’s Eve dinner together and talks about the past year.)" },
{ word: "年糕", meaning: "glutinous rice cake", example: "过年的时候，奶奶会做甜年糕给我们吃。(During the New Year, Grandma makes sweet rice cakes for us to eat.)" },
{ word: "发糕", meaning: "sponge cake; prosperity steamed rice cake", example: "发糕的「发」有发财、变好的意思。(In prosperity cake, the word “fa” has the meaning of getting rich and things getting better.)" },
{ word: "萝卜糕", meaning: "radish cake", example: "很多人过年喜欢煎萝卜糕当早餐。(Many people like to pan-fry radish cake as breakfast during the New Year.)" },
{ word: "年年有余", meaning: "to have surplus every year (New Year blessing)", example: "祝大家新的一年年年有余。(I wish everyone surplus year after year in the new year.)" },
{ word: "年年高升", meaning: "to get promoted year by year", example: "老师祝同学们成绩年年高升。(The teacher wishes the students’ grades to rise year after year.)" },
{ word: "平平安安", meaning: "to be safe and sound; peaceful and safe", example: "爸爸妈妈希望我们全家平平安安。(Mom and Dad hope our whole family will be safe and sound.)" },
{ word: "大吉大利", meaning: "to have great luck and great profit; lots of good fortune", example: "过年门口贴着「大吉大利」的春联。(At New Year, a “great luck and great profit” couplet is pasted on the door.)" }
];
